name: "Build Lib"
on: 
  workflow_dispatch:
      inputs:
        TargetPlatformName:
          description: 'Target platform'
          type: string
          required: true
  pull_request:
    branches:
      - releases/**
      - master
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
    branches:
      - releases/**
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare refs
        id: prep
        run: |
          VERSION=dev
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_REF == refs/heads/* ]]; then
            VERSION="sha-${GITHUB_SHA::8}"
          fi

          echo ::set-output name=version::${VERSION}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Build directory
        run: mkdir build

      - name: Run CMake
        run: cmake -S . -B build

      - name: Build with CMake
        run: cmake --build build

      - name: Archive build artifacts
        run: |
          zip -r output.zip build/MPMCQueueExample
        shell: bash
 
      - name: Extract version
        run: |
          WRT_SDK_VERSION_MAJOR=$(grep -oP 'set\(WRT_SDK_VERSION_MAJOR "\K[^"]+' CMakeLists.txt)
          WRT_SDK_VERSION_MINOR=$(grep -oP 'set\(WRT_SDK_VERSION_MINOR "\K[^"]+' CMakeLists.txt)
          WRT_SDK_VERSION_PATCH=$(grep -oP 'set\(WRT_SDK_VERSION_PATCH "\K[^"]+' CMakeLists.txt)
          WRT_SDK_VERSION_PRE_RELEASE=$(grep -oP 'set\(WRT_SDK_VERSION_PRE_RELEASE "\K[^"]+' CMakeLists.txt)
          # echo "VERSION=${WRT_SDK_VERSION_MAJOR}.${WRT_SDK_VERSION_MINOR}.${WRT_SDK_VERSION_PATCH}${WRT_SDK_VERSION_PRE_RELEASE}" >> $GITHUB_ENV

      - name: Print version
        run: echo "Version is $VERSION"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: "build-artifacts-${{ steps.prep.outputs.version }}"
          path: output.zip
        # if: startsWith(github.ref, 'refs/tags/')