name: "Build Lib"
on: 
  workflow_dispatch:
    inputs:
      repositoryREF:
        description: 'The branch, tag or SHA to checkout.'
        required: true
  # pull_request:
  #   branches:
  #     - releases/**
  #     - master
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
    branches:
      - releases/**
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rishiniranjan/mpmcqueue/imagename:latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          ref: ${{ github.event.inputs.repositoryREF }}

      - name: Prepare refs
        id: prep
        run: |
          if [[ "${{github.event.inputs.repositoryREF}}X" != "X" ]]; then
            VERSION=${{ github.event.inputs.repositoryREF }}
          elif [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION=$(git describe --long --tags --abbrev=10 --match "v*")
          fi

          echo ::set-output name=version::${VERSION}

      - name: Create Build directory
        run: mkdir build

      - name: Run CMake
        run: |
          touch build/MPMCQueueExample
      #   run: cmake -S . -B build
      
      # - name: Build with CMake
      #   run: cmake --build build

      - name: Archive build artifacts
        run: |
          zip -r output.zip build/MPMCQueueExample
        shell: bash

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: "build-artifacts-${{ steps.prep.outputs.version }}"
          path: output.zip
        # if: startsWith(github.ref, 'refs/tags/')