name: "Build Lib"
on: 
  workflow_dispatch:
      inputs:
        TargetPlatformName:
          description: 'Target platform'
          type: string
          required: true
  pull_request:
    branches:
      - releases/**
      - master
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
    branches:
      - releases/**
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare refs
        id: prep
        run: |
          VERSION=dev
          # if [[ $GITHUB_REF == refs/tags/* ]]; then
          #   VERSION=${GITHUB_REF#refs/tags/}
          # else
          #   VERSION=$(git describe --long --tags --abbrev=10 --match "v*")
          # fi
          echo ::set-output name=version::${VERSION}

      - name: Create Build directory
        run: mkdir build

      - name: Run CMake
        run: cmake -S . -B build

      - name: Build with CMake
        run: cmake --build build

      - name: Archive build artifacts
        run: |
          zip -r output.zip build/MPMCQueueExample
        shell: bash

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: "build-artifacts-${{ steps.prep.outputs.version }}"
          path: output.zip
        # if: startsWith(github.ref, 'refs/tags/')